language: go

go:
  - 1.5

after_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 2; fi

script:
  - go test -v .
  - go test -v ./reducers/
  - go test -v ./quadtree/
  - go test -v ./clustering/
